### PR TITLE
Introduce iterator caching to IntrusiveLinkedList

### PR DESCRIPTION
**Pull request by iamaleksey**
patch by Aleksey Yeschenko; reviewed by Blake Eggleston for CASSANDRA-18563

### CODE REVIEW

**Review by bdeggleston — APPROVED** [review]
+1

**Comment by belliottsmith** [comment]
Might seem silly, but could we confirm via a simple benchmark that this doesn’t regress easily inclined iterators, that might successfully use escape analysis through scalar replacement?

**Comment by iamaleksey** [comment]
@belliottsmith sure, will do before pushing the button on either of the two PRs.

**Comment by iamaleksey** [comment]
Pushed a JMH benchmark here: https://github.com/apache/cassandra/pull/2395/commits/82c7edcce501b56e8a714f7705382278a0961b50

Java 8 results:

```
Benchmark                                               (listSize)  Mode  Cnt    Score   Error  Units

IntrusiveLinkedListBench.iteratorCachingEnabled                  1  avgt   25    5.701 ± 0.268  ns/op
IntrusiveLinkedListBench.iteratorCachingEnabled                 10  avgt   25   25.288 ± 0.163  ns/op
IntrusiveLinkedListBench.iteratorCachingEnabled                100  avgt   25  269.721 ± 1.305  ns/op

IntrusiveLinkedListBench.iteratorCachingDisabled                 1  avgt   25    3.752 ± 0.021  ns/op
IntrusiveLinkedListBench.iteratorCachingDisabled                10  avgt   25   16.265 ± 0.063  ns/op
IntrusiveLinkedListBench.iteratorCachingDisabled               100  avgt   25  220.923 ± 8.237  ns/op

IntrusiveLinkedListBench.iteratorCachingNotImplemented           1  avgt   25    3.449 ± 0.011  ns/op
IntrusiveLinkedListBench.iteratorCachingNotImplemented          10  avgt   25   16.124 ± 0.153  ns/op
IntrusiveLinkedListBench.iteratorCachingNotImplemented         100  avgt   25  215.372 ± 1.000  ns/op
```

Java 11 results:

```
Benchmark                                               (listSize)  Mode  Cnt    Score   Error  Units

IntrusiveLinkedListBench.iteratorCachingEnabled                  1  avgt   25    4.292 ± 0.027  ns/op
IntrusiveLinkedListBench.iteratorCachingEnabled                 10  avgt   25   29.984 ± 0.066  ns/op
IntrusiveLinkedListBench.iteratorCachingEnabled                100  avgt   25  312.891 ± 0.918  ns/op

IntrusiveLinkedListBench.iteratorCachingDisabled                 1  avgt   25    2.448 ± 0.014  ns/op
IntrusiveLinkedListBench.iteratorCachingDisabled                10  avgt   25   10.245 ± 0.033  ns/op
IntrusiveLinkedListBench.iteratorCachingDisabled               100  avgt   25  154.932 ± 0.405  ns/op

IntrusiveLinkedListBench.iteratorCachingNotImplemented           1  avgt   25    2.354 ± 0.027  ns/op
IntrusiveLinkedListBench.iteratorCachingNotImplemented          10  avgt   25   10.122 ± 0.035  ns/op
IntrusiveLinkedListBench.iteratorCachingNotImplemented         100  avgt   25  154.551 ± 0.590  ns/op
```

**Comment by iamaleksey** [comment]
Running with `-prof=gc` shows no difference at all in allocation rates. Haven't gone profiling deeper / looking at asm, but I feel like this data is sufficient to show that your hunch has been correct, and both Java 8 and Java 11 are smart enough to optimise these away. And in the case of explicitly cached iterator, the additional loads + write to reset the iterator are actively harmful to performance.

**Pull request closed without merging**
